### ISSUE TITLE
Synthesis failed

### ISSUE THREAD

**Issue by luinxz** [mit-plv/fiat-crypto#834] opened 2020-07-07 08:26 UTC
Hi @JasonGross,

We appreciate your project, it's awesome.

I let you know about the new issues that @bbbrumley and I have found. When we try to get the arithmetic from Unsaturated Sorinas and our prime number has this form:

`p = 2^511 + 111`

And using these commands:
```console
unsaturated_solinas --static id_tc26_gost_3410_2012_512_paramSetB 64 9 '2^511 + 111'
unsaturated_solinas --static id_tc26_gost_3410_2012_512_paramSetB 64 10 '2^511 + 111'
unsaturated_solinas --static id_tc26_gost_3410_2012_512_paramSetB 64 '(auto)' '2^511 + 111'
```
The output is `Fatal error: exception Failure("Synthesis failed")` in each case.

Another case with the same output is:
```console
unsaturated_solinas --static SM2 64 '(auto)' '2^256 - 2^224 - 2^96 + 2^64 - 1'
```

But it gives us a new error:
```console
Error in converting fiat_SM2_to_bytes to C:
Final bounds check failed on second (carry) return value of Z.sub_with_get_borrow; expected an unsigned 1-bit number (relaxed to uint1), but found a int8.
```

But If we use the next commands, it works:
```console
word_by_word_montgomery --static id_tc26_gost_3410_2012_512_paramSetB 64 '2^511 + 111'
word_by_word_montgomery --static SM2 64 '2^256 - 2^224 - 2^96 + 2^64 - 1'
```
We only have this issue when there are **additions**. We'd like to use Unsaturated Sorinas instead of Montgomery.

Furthermore, we used the command `ulimit -S -s 1000000`

**Comment by JasonGross** [comment] 2020-07-07 13:41
If you request just `opp` (by adding `opp` to the end of the command line invocation), does it still fail?  If so, is probably a duplicate of https://github.com/mit-plv/fiat-crypto/issues/554#issuecomment-501414457 .  

> The output is Fatal error: exception Failure("Synthesis failed")

There should be more output than just this.  Perhaps on stdout rather than stderr.

My current expectation is that making unsaturated solinas work for these primes requires a different high-level template that's aware of the bounds, and there's not currently support for this kind of template (and I expect it'll be at least six months before I have time to consider looking into supporting this sort of template).  Why do you want unsaturated solinas for these primes?

**Comment by luinxz** [comment] 2020-07-07 19:37
Thank you for your prompt response. I think It's a duplicate of [#554 (comment)](https://github.com/mit-plv/fiat-crypto/issues/554#issuecomment-501414457). There is more output but it's similar to [#554 ](https://github.com/mit-plv/fiat-crypto/issues/554#issuecomment-501414457).

`unsaturated_solinas --static id_tc26_gost_3410_2012_512_paramSetB 64 '(auto)' '2^511 + 111' opp`
```c
check_args
/* Autogenerated: unsaturated_solinas --static id_tc26_gost_3410_2012_512_paramSetB 64 '(auto)' '2^511 + 111' opp */
/* curve description: id_tc26_gost_3410_2012_512_paramSetB */
/* machine_wordsize = 64 (from "64") */
/* requested operations: opp */
/* n = 9 (from "(auto)") */
/* s-c = 2^511 - [(1, -111)] (from "2^511 + 111") */
/* tight_bounds_multiplier = 1.1 (from "") */
/*  */
/* Computed values: */
/* carry_chain = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1] */
/* eval z = z[0] + (z[1] << 57) + (z[2] << 114) + (z[3] << 171) + (z[4] << 228) + (z[5] << 0x11d) + (z[6] << 0x156) + (z[7] << 0x18f) + (z[8] << 0x1c8) */
/* bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8) + (z[56] << 0x1c0) + (z[57] << 0x1c8) + (z[58] << 0x1d0) + (z[59] << 0x1d8) + (z[60] << 0x1e0) + (z[61] << 0x1e8) + (z[62] << 0x1f0) + (z[63] << 0x1f8) */

#include <stdint.h>

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif



In check_args
/* Autogenerated: unsaturated_solinas --static id_tc26_gost_3410_2012_512_paramSetB 64 '(auto)' '2^511 + 111' opp */
/* curve description: id_tc26_gost_3410_2012_512_paramSetB */
/* machine_wordsize = 64 (from "64") */
/* requested operations: opp */
/* n = 9 (from "(auto)") */
/* s-c = 2^511 - [(1, -111)] (from "2^511 + 111") */
/* tight_bounds_multiplier = 1.1 (from "") */
/*  */
/* Computed values: */
/* carry_chain = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1] */
/* eval z = z[0] + (z[1] << 57) + (z[2] << 114) + (z[3] << 171) + (z[4] << 228) + (z[5] << 0x11d) + (z[6] << 0x156) + (z[7] << 0x18f) + (z[8] << 0x1c8) */
/* bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8) + (z[56] << 0x1c0) + (z[57] << 0x1c8) + (z[58] << 0x1d0) + (z[59] << 0x1d8) + (z[60] << 0x1e0) + (z[61] << 0x1e8) + (z[62] << 0x1f0) + (z[63] << 0x1f8) */

#include <stdint.h>

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif
: Value not < (Associational.eval c ≤ 0) : expected 0 < -111


In fiat_id_tc26_gost_3410_2012_512_paramSetB_opp:
Computed bounds (Some [Some [-0x233333333333255 ~> 0xde], Some [-0x233333333333333 ~> 0x0], Some [-0x233333333333333 ~> 0x0], Some [-0x233333333333333 ~> 0x0], Some [-0x233333333333333 ~> 0x0], Some [-0x233333333333333 ~> 0x0], Some [-0x233333333333333 ~> 0x0], Some [-0x233333333333333 ~> 0x0], Some [0x73333333333334 ~> 0x100000000000000]]) are not tight enough (expected bounds not looser than (Some [Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x699999999999999], Some [0x0 ~> 0x1a6666666666664]])).
The bounds [-0x233333333333255 ~> 0xde] are looser than the expected bounds [0x0 ~> 0x699999999999999]
The bounds [-0x233333333333333 ~> 0x0] are looser than the expected bounds [0x0 ~> 0x699999999999999]
The bounds [-0x233333333333333 ~> 0x0] are looser than the expected bounds [0x0 ~> 0x699999999999999]
The bounds [-0x233333333333333 ~> 0x0] are looser than the expected bounds [0x0 ~> 0x699999999999999]
The bounds [-0x233333333333333 ~> 0x0] are looser than the expected bounds [0x0 ~> 0x699999999999999]
The bounds [-0x233333333333333 ~> 0x0] are looser than the expected bounds [0x0 ~> 0x699999999999999]
The bounds [-0x233333333333333 ~> 0x0] are looser than the expected bounds [0x0 ~> 0x699999999999999]
The bounds [-0x233333333333333 ~> 0x0] are looser than the expected bounds [0x0 ~> 0x699999999999999]
When doing bounds analysis on the syntax tree:
(λ x1,
  expr_let x2 := 222 - x1[0] (* : [-0x233333333333255 ~> 0xde] *) in
  expr_let x3 := -x1[1] (* : [-0x233333333333333 ~> 0x0] *) in
  expr_let x4 := -x1[2] (* : [-0x233333333333333 ~> 0x0] *) in
  expr_let x5 := -x1[3] (* : [-0x233333333333333 ~> 0x0] *) in
  expr_let x6 := -x1[4] (* : [-0x233333333333333 ~> 0x0] *) in
  expr_let x7 := -x1[5] (* : [-0x233333333333333 ~> 0x0] *) in
  expr_let x8 := -x1[6] (* : [-0x233333333333333 ~> 0x0] *) in
  expr_let x9 := -x1[7] (* : [-0x233333333333333 ~> 0x0] *) in
  expr_let x10 := 2^56 - x1[8] (* : [0x73333333333334 ~> 0x100000000000000] *) in
  ([-0x233333333333255 ~> 0xde])x2 :: ([-0x233333333333333 ~> 0x0])x3 :: ([-0x233333333333333 ~> 0x0])x4 :: ([-0x233333333333333 ~> 0x0])x5 :: ([-0x233333333333333 ~> 0x0])x6 :: ([-0x233333333333333 ~> 0x0])x7 :: ([-0x233333333333333 ~> 0x0])x8 :: ([-0x233333333333333 ~> 0x0])x9 :: ([0x73333333333334 ~> 0x100000000000000])x10 :: []
)

which can be pretty-printed as:
/*
 * Input Bounds:
 *   arg1: [[0x0 ~> 0x233333333333333], [0x0 ~> 0x233333333333333], [0x0 ~> 0x233333333333333], [0x0 ~> 0x233333333333333], [0x0 ~> 0x233333333333333], [0x0 ~> 0x233333333333333], [0x0 ~> 0x233333333333333], [0x0 ~> 0x233333333333333], [0x0 ~> 0x8ccccccccccccc]]
 * Output Bounds:
 *   out1: None
 */
void f(int128 out1[9], const uint64_t arg1[9]) {
  int64_t x1 = (UINT8_C(0xde) - (int64_t)(arg1[0]));
  int64_t x2 = (0x0 - (int64_t)(arg1[1]));
  int64_t x3 = (0x0 - (int64_t)(arg1[2]));
  int64_t x4 = (0x0 - (int64_t)(arg1[3]));
  int64_t x5 = (0x0 - (int64_t)(arg1[4]));
  int64_t x6 = (0x0 - (int64_t)(arg1[5]));
  int64_t x7 = (0x0 - (int64_t)(arg1[6]));
  int64_t x8 = (0x0 - (int64_t)(arg1[7]));
  uint64_t x9 = (UINT64_C(0x100000000000000) - (arg1[8]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
  out1[3] = x4;
  out1[4] = x5;
  out1[5] = x6;
  out1[6] = x7;
  out1[7] = x8;
  out1[8] = x9;
}

with input bounds (Some [Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x233333333333333], Some [0x0 ~> 0x8ccccccccccccc]]).

Fatal error: exception Failure("Synthesis failed")
```
`unsaturated_solinas --static SM2 64 '(auto)' '2^256 - 2^224 - 2^96 + 2^64 - 1' opp`
```c
check_args
/* Autogenerated: unsaturated_solinas --static SM2 64 '(auto)' '2^256 - 2^224 - 2^96 + 2^64 - 1' opp */
/* curve description: SM2 */
/* machine_wordsize = 64 (from "64") */
/* requested operations: opp */
/* n = 6 (from "(auto)") */
/* s-c = 2^256 - [(2^224, 1), (2^96, 1), (2^64, -1), (1, 1)] (from "2^256 - 2^224 - 2^96 + 2^64 - 1") */
/* tight_bounds_multiplier = 1.1 (from "") */
/*  */
/* Computed values: */
/* carry_chain = [4, 1, 0, 5, 5, 2, 1, 0, 3, 4, 5, 2, 1, 0] */
/* eval z = z[0] + (z[1] << 43) + (z[2] << 86) + (z[3] << 128) + (z[4] << 171) + (z[5] << 214) */
/* bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) */

#include <stdint.h>

#if (-1 & 3) != 3
#error "This code only works on a two's complement system"
#endif



In fiat_SM2_opp:
Computed bounds (Some [Some [0x73333333332 ~> 0xffffffffffe], Some [-0x8cccc8cccce ~> 0x3ffffe], Some [0x3999999919a ~> 0x7fffffff800], Some [0x73333333332 ~> 0xffffffffffe], Some [0x73333333332 ~> 0xffffffffffe], Some [0x39999999198 ~> 0x7fffffff7fe]]) are not tight enough (expected bounds not looser than (Some [Some [0x0 ~> 0x1a6666666664], Some [0x0 ~> 0x1a6666666664], Some [0x0 ~> 0xd3333333332], Some [0x0 ~> 0x1a6666666664], Some [0x0 ~> 0x1a6666666664], Some [0x0 ~> 0xd3333333332]])).
The bounds [-0x8cccc8cccce ~> 0x3ffffe] are looser than the expected bounds [0x0 ~> 0x1a6666666664]
When doing bounds analysis on the syntax tree:
(λ x1,
  expr_let x2 := 0xffffffffffe - x1[0] (* : [0x73333333332 ~> 0xffffffffffe] *) in
  expr_let x3 := 0x3ffffe - x1[1] (* : [-0x8cccc8cccce ~> 0x3ffffe] *) in
  expr_let x4 := 0x7fffffff800 - x1[2] (* : [0x3999999919a ~> 0x7fffffff800] *) in
  expr_let x5 := 0xffffffffffe - x1[3] (* : [0x73333333332 ~> 0xffffffffffe] *) in
  expr_let x6 := 0xffffffffffe - x1[4] (* : [0x73333333332 ~> 0xffffffffffe] *) in
  expr_let x7 := 0x7fffffff7fe - x1[5] (* : [0x39999999198 ~> 0x7fffffff7fe] *) in
  ([0x73333333332 ~> 0xffffffffffe])x2 :: ([-0x8cccc8cccce ~> 0x3ffffe])x3 :: ([0x3999999919a ~> 0x7fffffff800])x4 :: ([0x73333333332 ~> 0xffffffffffe])x5 :: ([0x73333333332 ~> 0xffffffffffe])x6 :: ([0x39999999198 ~> 0x7fffffff7fe])x7 :: []
)

which can be pretty-printed as:
/*
 * Input Bounds:
 *   arg1: [[0x0 ~> 0x8cccccccccc], [0x0 ~> 0x8cccccccccc], [0x0 ~> 0x46666666666], [0x0 ~> 0x8cccccccccc], [0x0 ~> 0x8cccccccccc], [0x0 ~> 0x46666666666]]
 * Output Bounds:
 *   out1: None
 */
void f(int128 out1[6], const uint64_t arg1[6]) {
  uint64_t x1 = (UINT64_C(0xffffffffffe) - (arg1[0]));
  int64_t x2 = (UINT32_C(0x3ffffe) - (int64_t)(arg1[1]));
  uint64_t x3 = (UINT64_C(0x7fffffff800) - (arg1[2]));
  uint64_t x4 = (UINT64_C(0xffffffffffe) - (arg1[3]));
  uint64_t x5 = (UINT64_C(0xffffffffffe) - (arg1[4]));
  uint64_t x6 = (UINT64_C(0x7fffffff7fe) - (arg1[5]));
  out1[0] = x1;
  out1[1] = x2;
  out1[2] = x3;
  out1[3] = x4;
  out1[4] = x5;
  out1[5] = x6;
}

with input bounds (Some [Some [0x0 ~> 0x8cccccccccc], Some [0x0 ~> 0x8cccccccccc], Some [0x0 ~> 0x46666666666], Some [0x0 ~> 0x8cccccccccc], Some [0x0 ~> 0x8cccccccccc], Some [0x0 ~> 0x46666666666]]).

Fatal error: exception Failure("Synthesis failed")
```

We want unsaturated Solinas for these primes because we get better timings with unsaturated Solinas than with Montgomery.

**Comment by JasonGross** [comment] 2020-07-07 19:44
> because we get better timings with unsaturated Solinas than with Montgomery.

I think this might depend on the shape of the prime?  cc @andres-erbsen , who knows more than I do about this.

In the meantime, I will close this issue as it does seem to be a duplicate of #554 (it's good to know that this is about the prime having ` +`, thanks!)

**Comment by JasonGross** [comment] 2020-07-07 19:44
Duplicate of #554

**Closed by JasonGross** 2020-07-07 19:44 UTC
