### ISSUE TITLE
Variable time code generated by Clang 10

### ISSUE THREAD

**Issue by chjj** [mit-plv/fiat-crypto#840] opened 2020-07-09 18:40 UTC
I found this while testing my [crypto library][1] with my [own version][2] of Adam Langley's [ctgrind][3]. Apparently, Clang's optimizer is much smarter than GCC's (i.e. too smart for its own good), and is producing variable time code for `fiat_*_cmovznz_*` when `-O3` is enabled. Seeing this jogged my memory of a [comment][4] from @davidben which mentioned this same thing. I guess I didn't think anything of it at the time.

@davidben's solution is to use a memory barrier, which might be the best solution (?).

A more naive fix seems to be marking the boolean as volatile:

``` diff
diff --git a/src/fields/p256_64.h b/src/fields/p256_64.h
index d84265f..09def2e 100644
--- a/src/fields/p256_64.h
+++ b/src/fields/p256_64.h
@@ -113,7 +113,7 @@ static void fiat_p256_mulx_u64(uint64_t* out1, uint64_t* out2, uint64_t arg1, ui
  *   out1: [0x0 ~> 0xffffffffffffffff]
  */
 static void fiat_p256_cmovznz_u64(uint64_t* out1, fiat_p256_uint1 arg1, uint64_t arg2, uint64_t arg3) {
-  fiat_p256_uint1 x1;
+  volatile fiat_p256_uint1 x1;
   uint64_t x2;
   uint64_t x3;
   x1 = (!(!arg1));
```

I figure @davidben's solution is probably better. In general, using a barrier doesn't seem to completely deoptimize code like `volatile` does, but it doesn't account for compilers which don't support GNU-style inline asm (though, I suppose it's assumed the compiler supports GNU extensions for any fiat backend which uses __int128). Assuming there is a compiler out there that optimizes as "well" as Clang without supporting GNU-style asm, `volatile` might be a better solution.

It's unfortunate there doesn't seem to be a really good one-size-fits-all solution for this. I haven't tested building with `--cmovnz-by-mul` yet, but I suspect it's the same story: I've tested switching some of my non-fiat-related functions to a multiplication with no luck.

I'd like to open up a discussion here to figure out more potential mitigations.

[1]: https://github.com/bcoin-org/libtorsion
[2]: https://github.com/bcoin-org/libtorsion/blob/master/test/ctgrind.c
[3]: https://github.com/agl/ctgrind
[4]: https://github.com/mit-plv/fiat-crypto/pull/723#issuecomment-613639650

**Comment by JasonGross** [comment] 2020-07-09 19:17
Duplicate of #748

**Closed by JasonGross** 2020-07-09 19:17 UTC
