### ISSUE TITLE
Unsaturated solinas fails on p256 too

### ISSUE THREAD

**Issue by miiip** [mit-plv/fiat-crypto#569] opened 2019-07-26 08:39 UTC
exception Failure("Synthesis failed") on:
` ./unsaturated_solinas 'p256' '8' '2^256 - 2^224 + 2^192 + 2^96 - 1' '32'`

The result:

Errors in converting fiat_p256_to_bytes to C:
Final bounds check failed on second argument to Z.sub_with_get_borrow; expected an unsigned 32-bit number (uint32), but found a uint64.
Final bounds check failed on third argument to Z.sub_with_get_borrow; expected an unsigned 32-bit number (uint32), but found a uint64.

Fatal error: exception Failure("Synthesis failed")

**Comment by JasonGross** [comment] 2019-08-02 01:01
I'm inclined to close this as invalid.  There is no such thing as 8-limb 32-bit unsaturated solinas for p256; it's a contradiction in terms.  Unsaturated means that each limb is strictly smaller than the bitwidth, but 256 / 8 = 32 which is not strictly less than 32.  If you want an earlier error message about a failed precondition, I can make the binary error earlier.  Is that what you're asking for here?

**Comment by JasonGross** [comment] 2019-08-02 03:55
(If there is in fact a performance gain and it's important to only inline some of the functions, I'm happy to make the change needed to allow that.)

**Comment by miiip** [comment] 2019-08-02 04:00
What exactly should be the number of limbs  for p256? It fails for 9,10,...16 or 27 limbs as well. The error message is the same.

**Comment by JasonGross** [comment] 2019-08-02 04:37
Ah, that is interesting.  I would expect it to work with something like 9 or 10 limbs.  I summon @andres-erbsen about it p256 should work with unsat solinas at all.  (Traditionally it is done with Montgomery, though there might be a way to make it work with saturated solinas (see https://github.com/mit-plv/fiat-crypto/issues/554#issuecomment-501414457 ))

**Comment by JasonGrossMIRI** [comment] 2019-08-02 07:45
@miiip no, the error is not the same for 9, 10, etc.  It only mentions uint64 for 8 limbs, and for >= 9 limbs, the error on to_bytes is
```
Error in converting fiat_p256_to_bytes to C:
Final bounds check failed on second (carry) return value of Z.sub_with_get_borrow; expected an unsigned 1-bit number (uint1), but found a int2.
```
This is exactly the same as the issue with p224

**Comment by JasonGross** [comment] 2019-08-02 07:46
@miiip no, the error is not the same for 9, 10, etc.  It only mentions uint64 for 8 limbs, and for >= 9 limbs, the error on to_bytes is
```
Error in converting fiat_p256_to_bytes to C:
Final bounds check failed on second (carry) return value of Z.sub_with_get_borrow; expected an unsigned 1-bit number (uint1), but found a int2.
```
This is exactly the same as the issue with p224

**Comment by JasonGross** [comment] 2019-08-02 07:46
Duplicate of #554

**Closed by JasonGross** 2019-08-02 07:46 UTC
