### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by ejgallego** [mit-plv/fiat-crypto#116] opened 2017-02-24 19:07 UTC
It seems that 60c90438bf9ab4cfbbdfd259783ff1a8fe1b2788 broke the build with 8.6.

**Comment by JasonGross** [comment] 2017-02-25 03:22
@andres-erbsen can you take a look at this?  I'll probably take a look Monday if you don't get to it before then.

**Comment by andres-erbsen** [comment] 2017-02-25 05:17
I looked and i couldn't figure out what's wrong from the Travis log. And worksforme.

On February 24, 2017 10:22:10 PM EST, Jason Gross <notifications@github.com> wrote:
>@andres-erbsen can you take a look at this?  I'll probably take a look
>Monday if you don't get to it before then.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mit-plv/fiat-crypto/issues/116#issuecomment-282456138

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JasonGross** [comment] 2017-02-27 19:08
The issue is that `PointEncoding.v` and `PointEncodingPre.v` got removed from `_CoqProject`.  Was that intentional?

**Comment by JasonGross** [comment] 2017-02-27 22:05
Closed by 2a50d6942f8b82bf8a0d5441a256bec9a1da7afc

**Closed by JasonGross** 2017-02-27 22:05 UTC

**Comment by ejgallego** [comment] 2017-02-27 22:12
Thanks a lot @JasonGross
